server:
  port: 8081

spring:
  application:
    name: graphql-dgs-trino-demo
  datasource:
    url: jdbc:trino://localhost:8080/memory/default
    username: admin
    password: 
    driver-class-name: io.trino.jdbc.TrinoDriver
  
dgs:
  graphql:
    graphiql:
      enabled: true
      path: /graphiql
    path: /graphql
    
logging:
  level:
    com.example.graphql: DEBUG
    com.netflix.graphql.dgs: DEBUG